//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPorCapas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMBUSTIBLE
    {
        public COMBUSTIBLE()
        {
            this.COCHES = new HashSet<COCH>();
        }
    
        public byte idCombustible { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<COCH> COCHES { get; set; }
    }
}
