//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPorCapas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTO
    {
        public int idDescuento { get; set; }
        public int LimiteTiempo { get; set; }
        public decimal Descuento1 { get; set; }
    }
}
