//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPorCapas.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlquilerCochesEntities : DbContext
    {
        public AlquilerCochesEntities()
            : base("name=AlquilerCochesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALQUILADO> ALQUILADOS { get; set; }
        public DbSet<CATEGORIA> CATEGORIAS { get; set; }
        public DbSet<CLIENTE> CLIENTES { get; set; }
        public DbSet<COCH> COCHES { get; set; }
        public DbSet<COMBUSTIBLE> COMBUSTIBLEs { get; set; }
        public DbSet<DESCUENTO> DESCUENTOS { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TIENDA> TIENDAS { get; set; }
        public DbSet<EntregasDevolucione> EntregasDevoluciones { get; set; }
    }
}
