//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPorCapas.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDA
    {
        public TIENDA()
        {
            this.ALQUILADOS = new HashSet<ALQUILADO>();
            this.COCHES = new HashSet<COCH>();
            this.EntregasDevoluciones = new HashSet<EntregasDevolucione>();
        }
    
        public int idTienda { get; set; }
        public string NombreTienda { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<ALQUILADO> ALQUILADOS { get; set; }
        public virtual ICollection<COCH> COCHES { get; set; }
        public virtual ICollection<EntregasDevolucione> EntregasDevoluciones { get; set; }
    }
}
